Traceback (most recent call last):
  File "/Users/johnross/Analysis-of-Wages-by-Education-in-the-U.S.A-1973-2022-/src/education_analysis.py", line 18, in <module>
    table_51 = pd.read_excel(xlsx_path, sheet_name='Table 5.1', skiprows=3, nrows=13)
  File "/Users/johnross/Analysis-of-Wages-by-Education-in-the-U.S.A-1973-2022-/.venv/lib/python3.13/site-packages/pandas/io/excel/_base.py", line 495, in read_excel
    io = ExcelFile(
        io,
    ...<2 lines>...
        engine_kwargs=engine_kwargs,
    )
  File "/Users/johnross/Analysis-of-Wages-by-Education-in-the-U.S.A-1973-2022-/.venv/lib/python3.13/site-packages/pandas/io/excel/_base.py", line 1550, in __init__
    ext = inspect_excel_format(
        content_or_path=path_or_buffer, storage_options=storage_options
    )
  File "/Users/johnross/Analysis-of-Wages-by-Education-in-the-U.S.A-1973-2022-/.venv/lib/python3.13/site-packages/pandas/io/excel/_base.py", line 1402, in inspect_excel_format
    with get_handle(
         ~~~~~~~~~~^
        content_or_path, "rb", storage_options=storage_options, is_text=False
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ) as handle:
    ^
  File "/Users/johnross/Analysis-of-Wages-by-Education-in-the-U.S.A-1973-2022-/.venv/lib/python3.13/site-packages/pandas/io/common.py", line 882, in get_handle
    handle = open(handle, ioargs.mode)
FileNotFoundError: [Errno 2] No such file or directory: '../Datasets/education.xlsx'
